name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  prerelease:
    runs-on: ubuntu-latest

    outputs:
      value: ${{ steps.prerelease.outputs.value }}

    steps:
    - name: Prerelease Check
      id: prerelease
      run: |
        if [[ ${{ github.ref_name }} =~ ^[0-9]+[.][0-9]+[.][0-9]+$ ]]; then
            echo value=false >> $GITHUB_OUTPUT
        else
            echo value=true >> $GITHUB_OUTPUT
        fi
  
  release:
    runs-on: ubuntu-latest

    needs:
    - prerelease

    steps:
      - name: Install just
        run: cargo install just

      - name: Check out code
        uses: actions/checkout@v4

      - name: Extract version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> "$GITHUB_ENV"

      - name: Patch version field in JSON
        run: |
          jq --arg v "$VERSION" '.version = $v' src/slipway_component.json > tmp && mv tmp src/slipway_component.json

      - name: Build release tarball
        run: just build-ci

      - name: Create GitHub release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ env.VERSION }}"
          draft: false
          prerelease: ${{ needs.prerelease.outputs.value }}
          files: "components/*.tar"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
